#
# Executes commands at login pre-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

#
# Browser
#

if [[ "$OSTYPE" == darwin* ]]; then
  export BROWSER='open'
fi

#
# Editors
#

export EDITOR='vim'
export VISUAL='vim'
export PAGER='less'

#
# Language
#

if [[ -z "$LANG" ]]; then
  export LANG='en_US.UTF-8'
fi

#
# Paths
#

typeset -gU cdpath fpath mailpath path

# Set the the list of directories that cd searches.
# cdpath=(
#   $cdpath
# )

# Set the list of directories that Zsh searches for programs.
path=(
  $HOME/.jenv/bin
  $HOME/.pyenv/bin
  $HOME/.cargo/bin
  $HOME/Workspace/ns-2-allinone/bin
  $HOME/Workspace/ns-2-allinone/tcl8.5.10/unix
  $HOME/Workspace/ns-2-allinone/tk8.5.10/unix
  /usr/local/{bin,sbin}
  /usr/local/sketch-1.7.5/sketch-frontend
  $path
)

export LD_LIBRARY_PATH=$HOME/Workspace/ns-2-allinone/otcl-1.14:$HOME/Workspace/ns-2-allinone/lib:$LD_LIBRARY_PATH
export TCL_LIBRARY=$HOME/Workspace/ns-2-allinone/tcl8.5.10/library

#
# Less
#

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
export LESS='-F -g -i -M -R -S -w -X -z-4'

# Set the Less input preprocessor.
if (( $+commands[lesspipe.sh] )); then
  export LESSOPEN='| /usr/bin/env lesspipe.sh %s 2>&-'
fi

export SKETCH_HOME=/usr/local/sketch-1.7.5/sketch-frontend/runtime
