#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# Load work zshrc
if [[ -d ~/.dotfiles-work ]]; then
  source ~/.dotfiles-work/zsh/zprezto-override/zshrc
fi

if [[ "$OSTYPE" == "linux-gnu" ]]; then
  export TERM=xterm-256color
  export PATH="/home/taegyunk/.pyenv/bin:$PATH"

elif [[ "$OSTYPE" == "darwin"* ]]; then

  # How to install dir_colors solarized
  # 1. brew install coreutils
  # 2. git clone git@github.com:seebi/dircolors-solarized.git
  # 3. cd dircolors-solarized
  # 4. ln -s ~/.dotfiles/dircolors-solarized/dircolors.256dark ~/.dir_colors
  # 5. insert following two lines in .zshrc
  eval `gdircolors ~/.dir_colors`
  if [[ -x /usr/local/bin/gls ]]; then
    alias ls='/usr/local/bin/gls --group-directories-first --color=auto'
  elif [[ -x ~/homebrew/bin/gls ]]; then
    alias ls='~/homebrew/bin/gls --group-directories-first --color=auto'
  fi

fi

# jenv
eval "$(jenv init -)"

# pyenv
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"

source /home/taegyunk/miniconda3/etc/profile.d/conda.sh

export SKETCH_HOME=/usr/local/sketch/sketch-frontend/runtime
