# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

if [[ "$OSTYPE" == "darwin"* ]]; then

  # How to install dir_colors solarized
  # 1. brew install coreutils
  # 2. git clone git@github.com:seebi/dircolors-solarized.git
  # 3. cd dircolors-solarized
  # 4. ln -s ~/.dotfiles/dircolors-solarized/dircolors.256dark ~/.dir_colors
  # 5. insert following two lines in .zshrc
  eval $(gdircolors ~/.dir_colors)
  if [[ -x /usr/local/bin/gls ]]; then
    alias ls='/usr/local/bin/gls --group-directories-first --color=auto'
  elif [[ -x ~/homebrew/bin/gls ]]; then
    alias ls='~/homebrew/bin/gls --group-directories-first --color=auto'
  fi
fi

if [[ -s ~/.mintty-colors-solarized ]]; then
  source ~/.mintty-colors-solarized/mintty-solarized-dark.sh
fi

if command -v jenv 1> /dev/null 2>&1; then
  eval "$(jenv init -)"
fi

if command -v rbenv 1> /dev/null 2>&1; then
  eval "$(rbenv init -)"
fi

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"                   # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && . "$NVM_DIR/bash_completion" # This loads nvm bash_completion

export WASMTIME_HOME="$HOME/.wasmtime"

export PATH="$WASMTIME_HOME/bin:$PATH"
# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/taegyunkim/google-cloud-sdk/path.zsh.inc' ]; then . '/Users/taegyunkim/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/taegyunkim/google-cloud-sdk/completion.zsh.inc' ]; then . '/Users/taegyunkim/google-cloud-sdk/completion.zsh.inc'; fi

# Check if 'kubectl' is a command in $PATH
if [ $commands[kubectl] ]; then

  # Placeholder 'kubectl' shell function:
  # Will only be executed on the first call to 'kubectl'
  kubectl() {

    # Remove this function, subsequent calls will execute 'kubectl' directly
    unfunction "$0"

    # Load auto-completion
    source <(kubectl completion zsh)

    # Execute 'kubectl' binary
    $0 "$@"
  }
fi

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
