if [[ "$OSTYPE" == darwin* ]]; then
  export BROWSER='open'
fi

export EDITOR='vim'
export VISUAL='vim'
export PAGER='less'

if [[ -z "$LANG" ]]; then
  export LANG='en_US.UTF-8'
fi

# Less
# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
export LESS='-F -g -i -M -R -S -w -X -z-4'

# Set the Less input preprocessor.
if (($ + commands[lesspipe.sh])); then
  export LESSOPEN='| /usr/bin/env lesspipe.sh %s 2>&-'
fi

# For NYU HPC
export MODULEPATH=$MODULEPATH:/usr/local/etc/modulefiles

# Set PATH, MANPATH, etc., for Homebrew.
if [ -x "/opt/homebrew/bin/brew" ]; then
  eval $(/opt/homebrew/bin/brew shellenv)
elif [ -x "/usr/local/bin/brew" ]; then
  eval $(/usr/local/bin/brew shellenv)
fi
