# Fig pre block. Keep at the top of this file.
[ -s "$HOME/.fig/shell/zprofile.pre.zsh" ] && . "$HOME/.fig/shell/zprofile.pre.zsh"
#
# Executes commands at login pre-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

#
# Browser
#

if [[ "$OSTYPE" == darwin* ]]; then
  export BROWSER='open'
fi

#
# Editors
#

export EDITOR='vim'
export VISUAL='vim'
export PAGER='less'

#
# Language
#

if [[ -z "$LANG" ]]; then
  export LANG='en_US.UTF-8'
fi

#
# Paths
#

typeset -gU cdpath fpath mailpath path

# Set the the list of directories that cd searches.
# cdpath=(
#   $cdpath
# )

export GOPATH=$HOME/golang
export PATH=$PATH:$GOPATH/bin

# Set the list of directories that Zsh searches for programs.
path=(
  $HOME/.cargo/bin
  $HOME/.rbenv/bin
  $HOME/.krew/bin
  $HOME/.local/bin
  $HOME/.wasme/bin
  /usr/local/{bin,sbin}
  /usr/local/go/bin
  $path
)

#
# Less
#

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
export LESS='-F -g -i -M -R -S -w -X -z-4'

# Set the Less input preprocessor.
if (( $+commands[lesspipe.sh] )); then
  export LESSOPEN='| /usr/bin/env lesspipe.sh %s 2>&-'
fi

export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init --path)"

export MODULEPATH=$MODULEPATH:/usr/local/etc/modulefiles

# Fig post block. Keep at the bottom of this file.
[ -s "$HOME/.fig/shell/zprofile.post.zsh" ] && .  "$HOME/.fig/shell/zprofile.post.zsh"
