# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# Antigen for zsh plugins/modules
if [[ -f "$HOME/.dotfiles/zsh/antigen/antigen.zsh" ]]; then
  source "$HOME/.dotfiles/zsh/antigen/antigen.zsh"
fi

NVM_LAZY=1
NVM_LAZY_CMD=('vim' 'nvim' 'code' 'npx')

antigen bundle ag
antigen bundle colored-man-pages
antigen bundle command-not-found
antigen bundle common-aliases
antigen bundle git
antigen bundle gnu-utils
antigen bundle nvm
antigen bundle mroth/evalcache
antigen bundle zsh-users/zsh-completions
antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle zsh-users/zsh-history-substring-search
antigen bundle zsh-users/zsh-autosuggestions

antigen theme romkatv/powerlevel10k

antigen apply

# powerlevel10k config, to customize prompt, run `p10k configure` or
# edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# zsh completion and history search
source ~/.dotfiles/zsh/completion.zsh
source ~/.dotfiles/zsh/history.zsh

# colorful ls command
if [[ -s "$HOME/.dir_colors" ]]; then
  if [[ $OSTYPE == 'darwin'* ]]; then
    alias dircolors=gdircolors
  fi
  eval $(dircolors "$HOME/.dir_colors")
fi
alias ls='ls --color=auto'

alias rebuds="bluetoothctl remove 34:82:C5:05:EE:48; bluetoothctl scan on; bluetoothctl pair 34:82:C5:05:EE:48; bluetoothctl connect 34:82:C5:05:EE:48"
alias resony="bluetoothctl remove F8:DF:15:45:B1:0E; bluetoothctl scan on; bluetoothctl pair F8:DF:15:45:B1:0E; bluetoothctl connect F8:DF:15:45:B1:0E"
alias brew='env PATH="${PATH//$(pyenv root)\/shims:/}" brew'
alias tm='tmux new -s `basename $PWD`'

bindkey -v '^?' backward-delete-char

# Pyenv installed with pyenv installer
export PYENV_ROOT="$HOME/.pyenv"
command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"
# Use evalcache to improve Zsh startup time
_evalcache pyenv init - --no-rehash --path
_evalcache pyenv virtualenv-init -

pyenv-brew-relink() {
  rm -f "$HOME/.pyenv/versions/*-brew"
  for i in $(brew --cellar)/python* ; do
    echo "$i"
    ln -s -f -v "$i" "$HOME/.pyenv/versions/${i##/*/}-brew"
  done
  pyenv rehash
}
source $(pyenv root)/completions/pyenv.zsh

export COURSIER_BIN_DIR="$HOME/.local/share/coursier/bin"
export PATH="$COURSIER_BIN_DIR:$PATH"

export PATH=/usr/local/cuda/bin${PATH:+:${PATH}}

if [[ $OSTYPE == 'linux-gnu' ]]; then
  export JAVA_HOME=/usr/lib/jvm/default-java
fi

# TODO: use https://github.com/matthieusb/zsh-sdkman for faster loading.
# https://github.com/sdkman/sdkman-cli/issues/977
# THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="$HOME/.sdkman"
[[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh"
